[package]
name = "lox-ast"
version = "0.1.0"
authors = ["Uncle Scientist <unclescientist@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
